// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using habitly.Models;

#nullable disable

namespace habitly.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("habitly.Models.Checkin", b =>
                {
                    b.Property<string>("IdCheckin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("date");

                    b.Property<string>("IdHabito")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCheckin");

                    b.HasIndex("IdHabito");

                    b.ToTable("Checkin");
                });

            modelBuilder.Entity("habitly.Models.Habito", b =>
                {
                    b.Property<string>("IdHabito")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescricaoHabito")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeHabito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusHabito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHabito");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Habito");
                });

            modelBuilder.Entity("habitly.Models.Metrica", b =>
                {
                    b.Property<string>("IdMetrica")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StreakAtual")
                        .HasColumnType("int");

                    b.Property<int>("StreakMaximo")
                        .HasColumnType("int");

                    b.HasKey("IdMetrica");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Metrica");
                });

            modelBuilder.Entity("habitly.Models.Notificacao", b =>
                {
                    b.Property<string>("IdNotificacao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificacao");
                });

            modelBuilder.Entity("habitly.Models.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("habitly.Models.Checkin", b =>
                {
                    b.HasOne("habitly.Models.Habito", "Habito")
                        .WithMany()
                        .HasForeignKey("IdHabito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("habitly.Models.Habito", b =>
                {
                    b.HasOne("habitly.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("habitly.Models.Metrica", b =>
                {
                    b.HasOne("habitly.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("habitly.Models.Notificacao", b =>
                {
                    b.HasOne("habitly.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
