// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dev_backend_habitly_eixo2.Models;

#nullable disable

namespace dev_backend_habitly_eixo2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023020640_AddPerfilColumn")]
    partial class AddPerfilColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Checkin", b =>
                {
                    b.Property<string>("IdCheckin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("date");

                    b.Property<string>("IdHabito")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCheckin");

                    b.HasIndex("IdHabito");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Habito", b =>
                {
                    b.Property<string>("IdHabito")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescricaoHabito")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodicidadeHabito")
                        .HasColumnType("int");

                    b.Property<string>("StatusHabito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloHabito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdHabito");

                    b.ToTable("Habitos");
                });

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Metrica", b =>
                {
                    b.Property<string>("IdMetrica")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreakAtual")
                        .HasColumnType("int");

                    b.Property<int>("StreakMaximo")
                        .HasColumnType("int");

                    b.HasKey("IdMetrica");

                    b.ToTable("Metricas");
                });

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Notificacao", b =>
                {
                    b.Property<string>("IdNotificacao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNotificacao");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Usuarios", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("dev_backend_habitly_eixo2.Models.Checkin", b =>
                {
                    b.HasOne("dev_backend_habitly_eixo2.Models.Habito", "Habito")
                        .WithMany()
                        .HasForeignKey("IdHabito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });
#pragma warning restore 612, 618
        }
    }
}
